import Foundation

enum AIPracticeAction: String, Codable { case start, answer, advance }

struct AIPendingRequest: Codable, Equatable {
    let id: UUID
    let action: AIPracticeAction
}

struct AIFeedback: Codable, Equatable {
    let revised: String
    let meaning: String
    let note: String
    /// Vocabulary the learner lacked in this sentence; auto-collected into 词库. Absent in 0.2 records.
    var items: [AILearningItem]? = nil
}

/// Same shape as the web `unfamiliar_english.items[]` (minus `original`).
struct AILearningItem: Codable, Equatable {
    let text: String
    let type: String // word | phrase | grammar
    let meaning: String

    var isValid: Bool {
        ["word", "phrase", "grammar"].contains(type)
            && !text.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty && text.count <= 80
            && !meaning.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty && meaning.count <= 120
    }
}

struct AIFeedbackRecord: Codable, Equatable, Identifiable {
    let id: UUID // The learner message being coached, including each retry.
    let stepIndex: Int
    let feedback: AIFeedback
}

struct AIPracticeTurn: Codable, Equatable {
    let reply: String
    let translation: String
    let hint: String
    let keywords: String
    let suggestedReply: String
    let suggestedMeaning: String
    let feedback: AIFeedback?

    func isValid(for action: AIPracticeAction) -> Bool {
        let values = [(reply, 1000), (translation, 1000), (hint, 400), (keywords, 200),
                      (suggestedReply, 800), (suggestedMeaning, 800)]
        guard values.allSatisfy({ !$0.0.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty && $0.0.count <= $0.1 }),
              (action == .answer) == (feedback != nil) else { return false }
        if let feedback {
            return [(feedback.revised, 800), (feedback.meaning, 800), (feedback.note, 500)]
                .allSatisfy { !$0.0.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty && $0.0.count <= $0.1 }
                && (feedback.items ?? []).count <= 3 && (feedback.items ?? []).allSatisfy(\.isValid)
        }
        return true
    }
}

struct AIPracticeState: Codable, Equatable {
    var pending: AIPendingRequest?
    var turn: AIPracticeTurn?
    var feedbacks: [AIFeedbackRecord] = []
    var model: String?
}

struct AIPracticeRequest: Codable {
    struct Scenario: Codable {
        let title: String
        let partner: String
        let partnerRole: String
        let setting: String
        let goals: [String]
    }
    struct Message: Codable {
        let role: PracticeMessage.Role
        let kind: PracticeMessage.Kind
        let text: String
        let stepIndex: Int
    }
    let requestId: UUID
    let sessionId: UUID
    let action: AIPracticeAction
    let stepIndex: Int
    let goal: String
    let context: String
    let scenario: Scenario
    let messages: [Message]
}

struct AIPracticeResponse: Codable {
    let requestId: UUID
    let model: String
    let data: AIPracticeTurn
}

struct AIScenarioRequest: Codable {
    let requestId: UUID
    let description: String
}

/// A learner-described scenario as generated by the server; becomes a local `PracticeScenario`.
struct AIScenarioResponse: Codable {
    struct Step: Codable {
        let goal, prompt, translation, hint, keywords, expression, meaning: String
    }
    struct Draft: Codable {
        let title, subtitle, category, partner, partnerRole, setting: String
        let steps: [Step]
    }
    let requestId: UUID
    let model: String
    let scenario: Draft

    func makeScenario(id: String = "custom-\(UUID().uuidString)") -> PracticeScenario? {
        let draft = scenario
        let texts = [draft.title, draft.subtitle, draft.category, draft.partner, draft.partnerRole, draft.setting]
            + draft.steps.flatMap { [$0.goal, $0.prompt, $0.translation, $0.hint, $0.keywords, $0.expression, $0.meaning] }
        guard draft.steps.count == 3, !model.isEmpty,
              texts.allSatisfy({ !$0.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty && $0.count <= 400 }) else { return nil }
        return PracticeScenario(id: id, title: draft.title, subtitle: draft.subtitle, category: draft.category,
            symbol: "text.bubble", partner: draft.partner, partnerRole: draft.partnerRole, setting: draft.setting,
            steps: draft.steps.enumerated().map { index, step in
                PracticeStep(id: "step-\(index)", goal: step.goal, prompt: step.prompt, translation: step.translation,
                    hint: step.hint, keywords: step.keywords, expression: step.expression, meaning: step.meaning)
            })
    }
}
